---
# tasks file for vector-role
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: ./vector_{{ vector_version }}.rpm
    mode: "0755"
- name: Instal vector
  become: true
  ansible.builtin.yum:
    disable_gpg_check: true
    name: ./vector_{{ vector_version }}.rpm
- name: Configure Vector
  become: true
  ansible.builtin.template:
    src: vector.j2
    mode: "0644"
    dest: /etc/vector/vector.yaml
  notify: Start vector service